---
title: "Estefy Fiallos"
---

# About Me

Welcome to my portfolio! I am a **data scientist** with experience in healthcare analytics, machine learning, and data visualization. My goal is to leverage data to improve decision-making and create impactful solutions.

---

# Work Projects

---

## PioneerRx Projects

### Support Issue Classification
- **Problem:** Manual support request routing was inefficient and labor-intensive.  
- **Solution:** Developed a machine learning system (LightGBM, logistic regression, random forest) with 94% accuracy to classify user requests. Integrated the model into SQL Server for automated routing.  
- **Impact:** Reduced human involvement by 74%, saving 300+ labor hours per month and improving customer resolution times.

---

### Prescription Directions Parser
- **Problem:** Manual processing of prescription directions slowed workflows.  
- **Solution:** Built Python RegEx logic to extract key prescription details like dose, frequency, and duration.  
- **Impact:** Enabled automated days' supply calculations and dose safety alerts, reducing manual errors and improving pharmacist workflows.

---

### HOA Interpretation for Long-Term Care Facilities
- **Problem:** Long-term care pharmacies needed precise medication administration records.  
- **Solution:** Developed a two-step method using Python RegEx and historical facility preferences to predict Hours of Administration (HOA).  
- **Impact:** Standardized records, reduced manual entry, and ensured facility-specific compliance.

---

### Medical Terminology Code Matching
- **Problem:** Manual matching of medical terminology codes (SNOMED, ICD-10) was time-consuming.  
- **Solution:** Used word mover's distance (Gensim) and fastText embeddings in Python to automate matching and SQL integration.  
- **Impact:** Streamlined workflows with pre-ranked code suggestions, reducing errors.

---

### Clinical Programs Data Cleaning and Analysis
- **Problem:** Analyzing 20+ clinical programs to measure medication adherence required complex data management.  
- **Solution:** Designed SQL processes to clean, validate, and analyze 1M+ patient records. Used Python (SciPy, Statsmodels) for statistical analysis.  
- **Impact:** Improved data quality, automated reimbursement validation, and identified adherence improvements.

---

### Finding Medication Adherence Factors
- **Problem:** Lack of control groups made adherence analysis inconclusive.  
- **Solution:** Used random forest models to identify key confounders and feature importance for accurate analysis.  
- **Impact:** Revealed critical factors influencing adherence and refined evaluation strategies.

---

### RxReady and MedSync Analysis
- **Problem:** Evaluating the impact of MedSync and refill reminders on pharmacy profitability.  
- **Solution:** Built mixed-effects models in Python to quantify feature impact while controlling for confounding factors.  
- **Impact:** Provided actionable equations for sales teams to promote profit gains to pharmacies.

---

### Pharmacy Desert Analysis

- **Problem:** Evaluate the impact of community pharmacies on pharmacy deserts in the US
- **Solution:** Conducted geospatial analysis using Python (geopandas) and census data to identify pharmacy deserts. Compare socioeconomic status of neighborhoods served by community vs. chain pharmacies using the Area Deprivation Index (ADI).
- **Impact:** Identified 69 million people living in pharmacy deserts, with an additional 28 million at risk if community pharmacies were removed. Highlighted the critical role of community pharmacies in serving socioeconomically disadvantaged areas, emphasizing their importance in addressing healthcare inequities.

---

# Personal Projects

## Predicting Heart Disease [github](https://github.com/estefyfb/Predicting-Heart-Disease)
- **Description:** The task is to predict whether a subject has heart disease based on 13 attributes using data from the [Heart Disease Data Set](https://archive.ics.uci.edu/ml/datasets/Heart+Disease).  
- **Technologies:** Python, K Nearest Neighbors Classifier, Logistic Regression, Random Forest Classifier.  
- **Highlights:** Implemented multiple classification models and analyzed feature importance to determine key predictors of heart disease.  
- **Dataset Size:** 303 observations, each representing a patient.

---